chore(deps): Bump vendor/bdwgc from `50abe55` to `19a7f49` (#476)
Bumps [vendor/bdwgc](https://github.com/bdwgc/bdwgc) from `50abe55` to
`19a7f49`.
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/19a7f495cd7c48cdf6f56c593c6dd57187afa079"><code>19a7f49</code></a>
Fix a typo (words duplication) in comment of backgraph.c</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/1b2b933b902dbb936b8e8bdf94512b28180a2891"><code>1b2b933</code></a>
Do not provide GC_win32_free_heap if GC_NO_DEINIT macro is defined</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/85128b6c97aaf672e524cd3c31494c2bf0b4c1b7"><code>85128b6</code></a>
Travis CI: Add testing of GC_NO_DEINIT macro</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/2f65e825a99f03d8e3472a301071f1b24df64ffb"><code>2f65e82</code></a>
Remove support of SEPARATE_GLOBALS macro</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/7b27a9d40b8370a0754f64a115eae4d65290afe2"><code>7b27a9d</code></a>
Allow the GC state to be re-initialized (in some configurations)</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/a958ea9e418b0631d018de47432cdf5b0dc8f730"><code>a958ea9</code></a>
Fix undefined reference to GC_objfreelist and GC_bytes_allocd</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/939fca4a3b228a1811221b6b5d5b65d4bb3fd71f"><code>939fca4</code></a>
Change last_back_trace_gc_no initialization to zero</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/c18b27e9339bd0bfb30e706583b519646691c8fe"><code>c18b27e</code></a>
Restore GC_interrupt_finalizers on return from GC_finalize_all</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/2e6a32f0bc0e09b7d54720ae7de79740d13ca317"><code>2e6a32f</code></a>
Use BZERO in GC_update_check_page</li>
<li><a
href="https://github.com/bdwgc/bdwgc/commit/3fdabe7443f0a90db9772a73bfd2f2ffdd2d93f8"><code>3fdabe7</code></a>
Reset GC_max_root_size value by GC_win32_free_heap</li>
<li>Additional commits viewable in <a
href="https://github.com/bdwgc/bdwgc/compare/50abe5579b66c2380bafb2a2f1abe60c68f2e574...19a7f495cd7c48cdf6f56c593c6dd57187afa079">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>